# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7b3ae04077bec9955fac0fc951cc7286e40ab1a69020616d17b575ba604e249d6c5e93d5f9222821f84e53ef56cef8e54b9f2b38a25a68e6e15037635464279

test:
  secret_key_base: 2f31e31113436d7a5267d65befcec4bdf80d5542267d055f66538d96f4792687c0380509e31e58d38eb015591be9d83437b990ccd2b035e542c32582342f73dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
